version: '3'
services:
  main_dev_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_humble_gazebo_kuka_iiwa
    image: kuka_iiwa_image:3.0
    volumes:
      - ../../ros2_gazebo_kuka_iiwa:/workspaces/ros2_gazebo_kuka_iiwa
    environment:
      - DISPLAY=host.docker.internal:0.0
    
    # Additional environment variables or settings if needed
    # ports:
    #   - "8080:80"  # Example port mapping

  # Add additional services if needed
  # another_service:
  #   image: some_image
  #   container_name: another_container
  #   ports:
  #     - "1234:5678"  # Example port mapping for another service
